name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc
      - name: Compile
        shell: msys2 {0}
        run: |
          gcc gui.c -o FredsFragcker.exe -mwindows -lcomctl32 -lpsapi -lcomdlg32 -lmsimg32
      - uses: actions/upload-artifact@v4
        with:
          name: FredsFragcker
          path: FredsFragcker.exe
